GRANT ALL PRIVILEGES ON *.* TO 'mysql_tunedlotto_user'@'localhost' IDENTIFIED BY PASSWORD '*EC30116FF4229A4842C3D6C7F4F9CEF8AA34C3A9' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `tuned_lotto_db`.* TO 'mysql_tunedlotto_user'@'localhost' WITH GRANT OPTION;